// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct ScAccountLogin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ScAccountLogin GetRootAsScAccountLogin(ByteBuffer _bb) { return GetRootAsScAccountLogin(_bb, new ScAccountLogin()); }
  public static ScAccountLogin GetRootAsScAccountLogin(ByteBuffer _bb, ScAccountLogin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ScAccountLogin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartScAccountLogin(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ScAccountLogin> EndScAccountLogin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ScAccountLogin>(o);
  }
};

