// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct ScPlayerBasic : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ScPlayerBasic GetRootAsScPlayerBasic(ByteBuffer _bb) { return GetRootAsScPlayerBasic(_bb, new ScPlayerBasic()); }
  public static ScPlayerBasic GetRootAsScPlayerBasic(ByteBuffer _bb, ScPlayerBasic obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ScPlayerBasic __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ScPlayerBasic> CreateScPlayerBasic(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      int level = 0) {
    builder.StartObject(2);
    ScPlayerBasic.AddLevel(builder, level);
    ScPlayerBasic.AddName(builder, nameOffset);
    return ScPlayerBasic.EndScPlayerBasic(builder);
  }

  public static void StartScPlayerBasic(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static Offset<ScPlayerBasic> EndScPlayerBasic(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ScPlayerBasic>(o);
  }
};

