// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct ScAccountLogin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ScAccountLogin GetRootAsScAccountLogin(ByteBuffer _bb) { return GetRootAsScAccountLogin(_bb, new ScAccountLogin()); }
  public static ScAccountLogin GetRootAsScAccountLogin(ByteBuffer _bb, ScAccountLogin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ScAccountLogin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MsgID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)10002; } }
  public int UserID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ScAccountLogin> CreateScAccountLogin(FlatBufferBuilder builder,
      int msgID = 10002,
      int userID = 0) {
    builder.StartObject(2);
    ScAccountLogin.AddUserID(builder, userID);
    ScAccountLogin.AddMsgID(builder, msgID);
    return ScAccountLogin.EndScAccountLogin(builder);
  }

  public static void StartScAccountLogin(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddMsgID(FlatBufferBuilder builder, int msgID) { builder.AddInt(0, msgID, 10002); }
  public static void AddUserID(FlatBufferBuilder builder, int userID) { builder.AddInt(1, userID, 0); }
  public static Offset<ScAccountLogin> EndScAccountLogin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ScAccountLogin>(o);
  }
};

