using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//伤害类型
public enum DamageType {

	DAMAGE_TYPE_NONE = 0,

	DAMAGE_TYPE_MAGICAL,

	DAMAGE_TYPE_PHYSICAL,

	DAMAGE_TYPE_PURE,

	DAMAGE_TYPE_ALL,

	DAMAGE_TYPE_REMOVAL
	
}

public enum DamageFlag{
	DAMAGE_FLAG_NONE = 0,

	DAMAGE_FLAG_IGNORES_MAGIC_ARMOR,

	DAMAGE_FLAG_IGNORES_PHISICAL_ARMOR,

	DAMAGE_FLAG_BYPASSES_INVULNERABILITY,

	DAMAGE_FLAG_BYPASSES_BLOCK,

	DAMAGE_FLAG_REFLECTION,

	DAMAGE_FLAG_HPLOSS,

	DAMAGE_FLAG_NO_DIRECTOR_EVENT,

	DAMAGE_FLAG_NON_LETHAL,

	DAMAGE_FLAG_USE_COMBAT_PROFICIENCY,

	DAMAGE_FLAG_NO_DAMAGE_MULTIPLIERS,
}

public enum SpellImmunityType
{
	SPELL_IMMUNITY_NONE = 0,

	SPELL_IMMUNITY_ENEMIES_YES,

	SPELL_IMMUNITY_ENEMIES_NO,

	SPELL_IMMUNITY_ALLIES_YES,

	SPELL_IMMUNITY_ALLIES_NO,
}

public struct ModifierAttribute
{
	public const int MODIFIER_ATTRIBUTE_NONE = 0;

	public const int MODIFIER_ATTRIBUTE_PERMANENT = 1;

	public const int MODIFIER_ATTRIBUTE_MULTIPLE = 2;

	public const int MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE = 4;

}

public enum Modifier_State{
	MODIFIER_STATE_ROOTED = 0,

	MODIFIER_STATE_DISARMED,

	MODIFIER_STATE_ATTACK_IMMUNE,

	MODIFIER_STATE_SILENCED,

	MODIFIER_STATE_MUTED,

	MODIFIER_STATE_STUNNED,

	MODIFIER_STATE_HEXED,

	MODIFIER_STATE_INVISIBLE,

	MODIFIER_STATE_INVULNERABLE,

	MODIFIER_STATE_MAGIC_IMMUNE,

	MODIFIER_STATE_PROVIDES_VISION,

	MODIFIER_STATE_NIGHTMARED,

	MODIFIER_STATE_BLOCK_DISABLED,

	MODIFIER_STATE_UNSELECTABLE,

	MODIFIER_STATE_CANNOT_MISS,

	MODIFIER_STATE_SPECIALLY_DENIABLE,

	MODIFIER_STATE_FROZEN,

	MODIFIER_STATE_COMMAND_RESTRICTED,

	MODIFIER_STATE_NOT_ON_MINIMAP,

	MODIFIER_STATE_NOT_ON_MINIMAP_FOR_ENEMIES,

	MODIFIER_STATE_LOW_ATTACK_PRIORITY,

	MODIFIER_STATE_NO_HEALTH_BAR,

	MODIFIER_STATE_FLYING,

	MODIFIER_STATE_NO_UNIT_COLLISION,

	MODIFIER_STATE_NO_TEAM_MOVE_TO,

	MODIFIER_STATE_NO_TEAM_SELECT,

	MODIFIER_STATE_PASSIVE_DISABLED,

	MODIFIER_STATE_DOMINATED,

	MODIFIER_STATE_BLIND,

	MODIFIER_STATE_OUT_OF_GAME,

	MODIFIER_STATEFAKE_ALLY,

	MODIFIER_STATE_FLYING_FOR_PATHING_PURPOSES_ONLY,

	MODIFIER_STATE_TRUESIGHT_IMMUNE,

	MODIFIER_STATE_LAST,

}

public enum Modifier_State_Value
{
	MODIFIER_STATE_VALUE_NO_ACTION,

	MODIFIER_STATE_VALUE_ENABLED,

	MODIFIER_STATE_VALUE_DISABLED,
}

public enum Modifier_Property
{
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE,

	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC,

	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT,

	MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE,

	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL,

	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL,

	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE,

	MODIFIER_PROPERTY_PROCATTACK_FEEDBACK,

	MODIFIER_PROPERTY_PRE_ATTACK,

	MODIFIER_PROPERTY_INVISIBILITY_LEVEL,

	MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY,

	MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT,

	MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE,

	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE,

	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE,

	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE_2,

	MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE,

	MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE_2,

	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE,

	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN,

	MODIFIER_PROPERTY_MOVESPEED_LIMIT,

	MODIFIER_PROPERTY_MOVESPEED_MAX,

	MODIFIER_PROPERTY_ATTACKSPEED_BASE_OVERRIDE,

	MODIFIER_PROPERTY_FIXED_ATTACK_RATE,

	MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT,

	MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT,

	MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT,

	MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT,

	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE,

	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION,

	MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE,

	MODIFIER_PROPERTY_SPELL_AMPLITY_PERCENTAGE,

	MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE,

	MODIFIER_PROPERTY_MAGICDAMAGEOUTGOING_PERCENTAGE,

	MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE,

	MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE,

	MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE,

	MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE,

	MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT,

	MODIFIER_PROPERTY_EVASION_CONSTANT,

	MODIFIER_PROPERTY_NEGATIVE_EVASION_CONSTANT,

	MODIFIER_PROPERTY_AVOID_DAMAGE,

	MODIFIER_PROPERTY_AVOID_SPELL,

	MODIFIER_PROPERTY_MISS_PERCENTAGE,

	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS,

	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE,

	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE,

	MODIFIER_PROPERTY_IGNORE_PHYSICAL_ARMOR,

	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DIRECT_MODIFICATION,

	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS,

	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE,

	MODIFIER_PROPERTY_BASE_MANA_REGEN,

	MODIFIER_PROPERTY_MANA_REGEN_CONSTANT,

	MODIFIER_PROPERTY_MANA_REGEN_PERCENTAGE,

	MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE,

	MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT,

	MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE,

	MODIFIER_PROPERTY_HEALTH_BONUS,

	MODIFIER_PROPERTY_MANA_BONUS,

	MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS,

	MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS,

	MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE,

	MODIFIER_PROPERTY_STATS_STRENGTH_BONUS,

	MODIFIER_PROPERTY_STATS_AGILITY_BONUS,

	MODIFIER_PROPERTY_STATS_INTELLECT_BONUS,

	MODIFIER_PROPERTY_CAST_RANGE_BONUS,

	MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING,

	MODIFIER_PROPERTY_ATTACK_RANGE_BONUS,

	MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_UNIQUE,

	MODIFIER_PROPERTY_MAX_ATTACK_RANGE,

	MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS,

	MODIFIER_PROPERTY_REINCARNATION,

	MODIFIER_PROPERTY_RESPAWNTIME,

	MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE,

	MODIFIER_PROPERTY_RESPAWNTIME_STACKING,

	MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE,

	MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING,

	MODIFIER_PROPERTY_CASTTIME_PERCENTAGE,

	MODIFIER_PROPERTY_MANACOST_PERCENTAGE,

	MODIFIER_PROPERTY_DEATHGOLDCOST,

	MODIFIER_PROPERTY_EXP_RATE_BOOST,

	MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE,

	MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE,

	MODIFIER_PROPERTY_MAGICAL_CONSTANT_BLOCK,

	MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK,

	MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_SPECIAL,

	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR,

	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK,

	MODIFIER_PROPERTY_OVERRIDE_ANIMATION,

	MODIFIER_PROPERTY_OVERRIDE_ANIMATION_WEIGHT,

	MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE,

	MODIFIER_PROPERTY_ABSORB_SPELL,

	MODIFIER_PROPERTY_REFLECT_SPELL,

	MODIFIER_PROPERTY_DISABLE_AUTOATTACK,

	MODIFIER_PROPERTY_BONUS_DAY_VISION,

	MODIFIER_PROPERTY_BONUS_NIGHT_VISION,

	MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE,

	MODIFIER_PROPERTY_FIXED_DAY_VISION,

	MODIFIER_PROPERTY_FIXED_NIGHT_VISION,

	MODIFIER_PROPERTY_MIN_HEALTH,

	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL,

	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL,

	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE,

	MODIFIER_PROPERTY_IS_ILLUSION,

	MODIFIER_PROPERTY_ILLUSION_LABEL,

	MODIFIER_PROPERTY_SUPER_ILLUSION,

	MODIFIER_PROPERTY_SUPRE_ILLUSION_WITH_ULTIMATE,

	MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE,

	MODIFIER_PROPERTY_DISABLE_HEALING, //无法恢复生命值

	MODIFIER_PROPERTY_ALWAYS_ALLOW_ATTACK,

	MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL,

	MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH,

	MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER,

	MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER,

	MODIFIER_PROPERTY_STATUS_RESISTANCE_BONUS,

}

public enum EffectAttachType
{
	FOLLOW_ORIGIN,

	FOLLOW_OVERHEAD,

	FOLLOW_HITLOC,

	ATTACH_ATTACK,

	ATTACH_ATTACK1,

	WORLD_ORIGIN,

	START_AT_CUSTOMORIGIN,

}

public enum AnimationState{
	ACT_IDLE,
	ACT_RUN,
	ACT_ATTACK_01,
}

public enum OrbPriority
{
	DOTA_ORB_PRIORITY_ABILITY = 1,
	DOTA_ORB_PRIORITY_ITEM = 2,
}

public enum UNIT_CAP_ATTACK
{
	UNIT_CAP_NO_ATTACK = 0,
	UNIT_CAP_MELEE_ATTACK = 1,
	UNIT_CAP_RANGED_ATTACK = 2,
}

public enum MainAttribute
{
	ATTRIBUTE_INVALID = 0,

	ATTRIBUTE_STRENGTH = 1,

	ATTRIBUTE_AGILITY = 2,

	ATTRIBUTE_INTELLECT = 3,

	ATTRIBUTE_MAX = 4,

}

public enum UnitMoveCapability
{
	UNIT_CAP_MOVE_NONE = 0,

	UNIT_CAP_MOVE_GROUND = 1,

	UNIT_CAP_MOVE_FLY = 2,
}

public enum HullSizeType
{
	HULL_SIZE_SMALL = 1,

	HULL_SIZE_REGULAR = 2,

	HULL_SIZE_SIEGE = 3,

	HULL_SIZE_HERO = 4,

	HULL_SIZE_HUGE = 5,

	HULL_SIZE_BUILDING = 6,

	HULL_SIZE_FILTER = 7,

	HULL_SIZE_BARRACKS = 8,

	HULL_SIZETOWER = 9,
}